# Generated by Django 4.2.1 on 2023-05-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('total_credit', models.IntegerField()),
                ('practical_credit', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateField()),
                ('room_number', models.IntegerField()),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.building')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('avarage_star', models.FloatField(blank=True, null=True)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ins_dept', to='vahedhub.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('BuildingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.building')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.course')),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.exam')),
                ('InstructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('entry_year', models.IntegerField()),
                ('passed_credit', models.IntegerField()),
                ('GPA', models.FloatField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('gender', models.BooleanField()),
                ('date_of_birth', models.DateField()),
                ('avarage_star', models.FloatField(blank=True, null=True)),
                ('DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.department')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('SectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.section')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.student')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCourses',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('selected_sections', models.TextField()),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.student')),
            ],
        ),
        migrations.CreateModel(
            name='Section_TimeSlot',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('SectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.section')),
                ('TimeSlotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='TermID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.term'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('like_number', models.IntegerField()),
                ('dislike_number', models.IntegerField()),
                ('Question_text', models.CharField(max_length=500)),
                ('InstructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.instructor')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('display_stu', models.BooleanField()),
                ('display_avg', models.BooleanField()),
                ('like_number', models.IntegerField()),
                ('dislike_number', models.IntegerField()),
                ('comment_text', models.CharField(max_length=500)),
                ('InstructorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vahedhub.instructor')),
                ('StudentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vahedhub.student')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('like_number', models.IntegerField()),
                ('dislike_number', models.IntegerField()),
                ('answer_text', models.CharField(max_length=500)),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.question')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vahedhub.student')),
            ],
        ),
    ]
